### PR TITLE
Support AVX512 on stable Rust

### LINKED ISSUE #758: AVX-512 support on `stable`
Per #757, `avx512_target_feature` will soon be stable on Rust 1.89. See also FCP for AVX-512 support: https://github.com/rust-lang/rust/issues/111137#issuecomment-2888077126

Given that, it will soon be possible to support AVX-512 on `stable` rather than as a `nightly`-only feature. With the target feature stable, any unstable intrinsics can be worked around by using inline ASM, which can be implemented in the form of "polyfills" which look identical to the unstable intrinsics. Though hopefully when that FCP completes, the relevant intrinsics will be stable soon after.

### PR DESCRIPTION
**Pull request by nazar-pc**
I took https://github.com/dalek-cryptography/curve25519-dalek/pull/866 as is, rebased it on `main` and fixed it up in the last two commits. The last two commits are the only changes compared to https://github.com/dalek-cryptography/curve25519-dalek/pull/866.

https://github.com/RustCrypto/actions/blob/master/intel-sde-install/action.yaml turned out to be useless due to `813591` hardcoded in it, so I followed example from https://github.com/RustCrypto/stream-ciphers/blob/2aa613ea7007e4756a31c2951dfd1023266ec960/.github/workflows/chacha20.yml#L80-L118

I have not changed anything that wasn't required to get things running, but I had to fix a few bugs and can confirm it now passes existing tests on my Zen 4 CPU with `-C target-cpu=znver4`.

I did hit https://github.com/dalek-cryptography/curve25519-dalek/issues/912 in the process though, but it doesn't seem to be tested in CI, so :shrug:.

I'd love to see runtime detection for AVX512 in addition to compile-time check, however it is beyond simply making things work on stable.

Fixes https://github.com/dalek-cryptography/curve25519-dalek/issues/758, closes https://github.com/dalek-cryptography/curve25519-dalek/pull/866

### CODE REVIEW

**Comment by tarcieri** [comment]
FYI, I *just* fixed https://github.com/RustCrypto/actions/tree/master/intel-sde-install

All it needs is:

```yaml
- uses: RustCrypto/actions/intel-sde-install@master
```

**Comment by tarcieri** [comment]
@rozbb IMO this is worth getting into the v5.0.0 release

**Comment by nazar-pc** [comment]
Done, all tests pass now. Let me know if further changes are needed, I should be able to make them. Or feel free to push on top, you should have permissions to do so.

File: .github/workflows/curve25519-dalek.yml [hunk 1]
```diff
@@ -19,6 +19,9 @@ defaults:
 env:
   CARGO_TERM_COLOR: always
   RUSTFLAGS: '-D warnings'
+  # NOTE: The mirror number changes with each version so keep these in sync
+  SDE_FULL_VERSION_MIRROR: '915934'
+  SDE_FULL_VERSION: '10.8.0-2026-03-15'
```
Comment (tarcieri) [inline .github/workflows/curve25519-dalek.yml]: These aren't needed any more

**Review by tarcieri — APPROVED** [review]

**Comment by tarcieri** [comment]
Hmm strange, saw this build failure on nightly after merging: https://github.com/dalek-cryptography/curve25519-dalek/actions/runs/28380522785/job/84081560067

cc @nazar-pc @rozbb 

```
error[E0433]: cannot find `spec_avx512ifma_avx512vl` in `precomputed_straus`
   --> curve25519-dalek/src/backend.rs:105:49
    |
105 |         vector::scalar_mul::precomputed_straus::spec_avx512ifma_avx512vl::VartimePrecomputedStraus,
    |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^ could not find `spec_avx512ifma_avx512vl` in `precomputed_straus`
    |
note: found an item that was configured out
   --> curve25519-dalek/src/backend/vector/scalar_mul/precomputed_straus.rs:18:9
    |
 14 | / #[curve25519_dalek_derive::unsafe_target_feature_specialize(
 15 | |     "avx2",
 16 | |     conditional("avx512ifma,avx512vl", curve25519_dalek_backend = "avx512")
    | |_____________________________________- the item is gated behind the `avx512ifma` feature
 17 |   )]
 18 |   pub mod spec {
    |           ^^^^
```
